### ISSUE TITLE
Failed to create service instance

### ISSUE THREAD

**Issue by jiangchuan1220** [cloudfoundry-incubator/brooklyn-service-broker#17]
I added an catalog in my brooklyn environment. I am sure it can succeed to deploy from brooklyn UI. But when I try to deploy it from brooklyn broker, it failed. When I check the blueprint, I found it is not using the blueprint I configured.
I used the following catalog blueprint to add a catalog 
```
brooklyn.catalog:
  id: Icinga2
  version: 1.0
  itemType: template
  name: Icinga2
  description: Icinga2 is an open source monitoring tool.
  item:
    services:
    - type: com.services.icinga2.Icinga2Service
      name: Icinga Node
      provisioning.properties:
        imageNameRegex: ubuntu-14.04-LTS
        hardwareId: t2.micro
      adminpassword: abc123456
      services: ssh,procs,load,swap
      hosts: 127.0.0.1
    location:
      jclouds:aws-ec2:
        identity: ******
        credential: ******
        region: ap-southeast-1
```
I tested to deploy it from brooklyn UI, it succeed to deploy using the blueprint I configured in the item. It is shown as follows:

```
    services:
    - type: com.services.icinga2.Icinga2Service
      name: Icinga Node
      provisioning.properties:
        imageNameRegex: ubuntu-14.04-LTS
        hardwareId: t2.micro
      adminpassword: abc123456
      services: ssh,procs,load,swap
      hosts: 127.0.0.1
    location:
      jclouds:aws-ec2:
        identity: ******
        credential: ******
        region: ap-southeast-1
```
But when I deploy it from broker, It failed and I found it is not using the blueprint I configured in the item. It is just using the following blueprint:
```
{"services":[{"type": "Icinga2:1.0"}], "locations": ["jclouds:aws-ec2"]}
```
